<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Menu;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $dessert  = Category::where('slug', 'dessert')->first();
        $makanan  = Category::where('slug', 'makanan')->first();
        $snack    = Category::where('slug', 'snack')->first();
        $kopi     = Category::where('slug', 'kopi')->first();
        $nonKopi  = Category::where('slug', 'non-kopi')->first();

        $menus = [
            // ─── DESSERT ─── (menu unggulan klien: is_featured=true, is_sample=false)
            [
                'category_id'   => $dessert?->id,
                'name'          => 'Banoffee',
                'slug'          => 'banoffee',
                'description'   => 'Dessert ikonik Nucomu — perpaduan karamel, pisang, dan krim lembut di atas base biskuit renyah. Citarasa otentik yang jadi asal-mula lahirnya Nucomu Cafe.',
                'price'         => 28000,
                'is_available'  => true,
                'is_featured'   => true,
                'is_best_seller'=> true,
                'is_sample'     => false,
                'sort_order'    => 1,
            ],
            [
                'category_id'   => $dessert?->id,
                'name'          => 'Cheesecake',
                'slug'          => 'cheesecake',
                'description'   => 'Cheesecake creamy dengan tekstur lembut berpadu rasa keju yang kaya. Satu gigitan langsung bikin nagih.',
                'price'         => 27000,
                'is_available'  => true,
                'is_featured'   => true,
                'is_best_seller'=> true,
                'is_sample'     => false,
                'sort_order'    => 2,
            ],
            [
                'category_id'   => $dessert?->id,
                'name'          => 'Tiramisu',
                'slug'          => 'tiramisu',
                'description'   => 'Tiramisu klasik dengan lapisan mascarpone tebal, taburan bubuk cokelat, dan aroma kopi yang menggoda.',
                'price'         => 27000,
                'is_available'  => true,
                'is_featured'   => true,
                'is_best_seller'=> false,
                'is_sample'     => false,
                'sort_order'    => 3,
            ],
            [
                'category_id'   => $dessert?->id,
                'name'          => 'Donut Choco Pistachio',
                'slug'          => 'donut-choco-pistachio',
                'description'   => 'Donut lembut berlapis cokelat gelap dengan taburan pistachio renyah. Kombinasi sempurna antara manis, gurih, dan crunch.',
                'price'         => 22000,
                'is_available'  => true,
                'is_featured'   => true,
                'is_best_seller'=> false,
                'is_sample'     => false,
                'sort_order'    => 4,
            ],
            // DATA CONTOH dessert tambahan (is_sample=true)
            [
                'category_id'   => $dessert?->id,
                'name'          => 'Brownies Fudge',
                'slug'          => 'brownies-fudge',
                'description'   => 'Brownies padat dengan cokelat premium, lembut di dalam dan sedikit renyah di luar.',
                'price'         => 20000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 5,
            ],
            [
                'category_id'   => $dessert?->id,
                'name'          => 'Pudding Matcha',
                'slug'          => 'pudding-matcha',
                'description'   => 'Pudding lembut berbahan matcha premium Jepang, disajikan dingin dengan saus karamel tipis.',
                'price'         => 18000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 6,
            ],
            [
                'category_id'   => $dessert?->id,
                'name'          => 'Crepe Cake Berry',
                'slug'          => 'crepe-cake-berry',
                'description'   => 'Lapisan crepe tipis dengan krim vanila lembut dan potongan buah berry segar.',
                'price'         => 32000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 7,
            ],

            // ─── MAKANAN ─── (unggulan klien)
            [
                'category_id'   => $makanan?->id,
                'name'          => 'Nasi Cakalang Suwir',
                'slug'          => 'nasi-cakalang-suwir',
                'description'   => 'Nasi putih pulen disajikan bersama cakalang suwir pedas gurih khas Manado, dilengkapi lauk pelengkap.',
                'price'         => 35000,
                'is_available'  => true,
                'is_featured'   => true,
                'is_best_seller'=> true,
                'is_sample'     => false,
                'sort_order'    => 1,
            ],
            [
                'category_id'   => $makanan?->id,
                'name'          => 'Rice Bowl Ayam Cabe Garam',
                'slug'          => 'rice-bowl-ayam-cabe-garam',
                'description'   => 'Rice bowl dengan potongan ayam crispy bumbu cabe garam yang gurih dan sedikit pedas menggoda.',
                'price'         => 32000,
                'is_available'  => true,
                'is_featured'   => true,
                'is_best_seller'=> false,
                'is_sample'     => false,
                'sort_order'    => 2,
            ],
            // DATA CONTOH makanan tambahan
            [
                'category_id'   => $makanan?->id,
                'name'          => 'Nasi Goreng Kampung',
                'slug'          => 'nasi-goreng-kampung',
                'description'   => 'Nasi goreng dengan bumbu tradisional, dilengkapi telur dan kerupuk renyah.',
                'price'         => 28000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 3,
            ],
            [
                'category_id'   => $makanan?->id,
                'name'          => 'Sandwich Club',
                'slug'          => 'sandwich-club',
                'description'   => 'Sandwich dengan isian ayam, selada segar, tomat, dan saus spesial diapit roti gandum panggang.',
                'price'         => 30000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 4,
            ],
            [
                'category_id'   => $makanan?->id,
                'name'          => 'Pasta Aglio Olio',
                'slug'          => 'pasta-aglio-olio',
                'description'   => 'Pasta spaghetti dengan minyak zaitun, bawang putih, cabai, dan taburan keju parmesan.',
                'price'         => 33000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 5,
            ],

            // ─── SNACK ───
            [
                'category_id'   => $snack?->id,
                'name'          => 'Kentang Goreng Crispy',
                'slug'          => 'kentang-goreng-crispy',
                'description'   => 'Kentang goreng renyah dengan bumbu balado atau original, disajikan dengan saus keju leleh.',
                'price'         => 18000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 1,
            ],
            [
                'category_id'   => $snack?->id,
                'name'          => 'Roti Bakar Cokelat Keju',
                'slug'          => 'roti-bakar-cokelat-keju',
                'description'   => 'Roti tawar panggang dengan olesan cokelat dan lelehan keju melimpah di atasnya.',
                'price'         => 15000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 2,
            ],
            [
                'category_id'   => $snack?->id,
                'name'          => 'Pisang Goreng Kremes',
                'slug'          => 'pisang-goreng-kremes',
                'description'   => 'Pisang kepok yang digoreng dengan kremes crispy dan taburan bubuk kayu manis, disajikan hangat.',
                'price'         => 13000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 3,
            ],
            [
                'category_id'   => $snack?->id,
                'name'          => 'Chicken Nugget',
                'slug'          => 'chicken-nugget',
                'description'   => 'Nugget ayam crispy dengan saus cabai manis dan saus keju, cocok sebagai teman ngopi.',
                'price'         => 20000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 4,
            ],

            // ─── KOPI ─── (unggulan klien)
            [
                'category_id'   => $kopi?->id,
                'name'          => 'Nucomu Coffee',
                'slug'          => 'nucomu-coffee',
                'description'   => 'Kopi signature Nucomu dengan blend spesial yang memberikan cita rasa seimbang antara asam dan pahit, cocok dinikmati kapan saja.',
                'price'         => 25000,
                'is_available'  => true,
                'is_featured'   => true,
                'is_best_seller'=> true,
                'is_sample'     => false,
                'sort_order'    => 1,
            ],
            [
                'category_id'   => $kopi?->id,
                'name'          => 'Butterscloud',
                'slug'          => 'butterscloud',
                'description'   => 'Minuman kopi dengan foam butter lembut di atas, perpaduan antara espresso kuat dan cloud foam manis yang dreamy.',
                'price'         => 28000,
                'is_available'  => true,
                'is_featured'   => true,
                'is_best_seller'=> false,
                'is_sample'     => false,
                'sort_order'    => 2,
            ],
            // DATA CONTOH kopi tambahan
            [
                'category_id'   => $kopi?->id,
                'name'          => 'Americano',
                'slug'          => 'americano',
                'description'   => 'Espresso double shot dengan air panas, menghasilkan kopi hitam yang kuat dan refreshing.',
                'price'         => 20000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 3,
            ],
            [
                'category_id'   => $kopi?->id,
                'name'          => 'Cappuccino',
                'slug'          => 'cappuccino',
                'description'   => 'Espresso dengan susu panas dan foam susu tebal, klasik dan selalu memuaskan.',
                'price'         => 22000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 4,
            ],
            [
                'category_id'   => $kopi?->id,
                'name'          => 'Caramel Latte',
                'slug'          => 'caramel-latte',
                'description'   => 'Latte espresso dengan sirup karamel manis dan susu lembut, ditutup drizzle karamel di atasnya.',
                'price'         => 26000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 5,
            ],
            [
                'category_id'   => $kopi?->id,
                'name'          => 'Cold Brew',
                'slug'          => 'cold-brew',
                'description'   => 'Kopi cold brew 12 jam dengan rasa smooth dan rendah asam, disajikan dingin tanpa es.',
                'price'         => 27000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 6,
            ],

            // ─── NON-KOPI ─── (unggulan klien)
            [
                'category_id'   => $nonKopi?->id,
                'name'          => 'Lychee Tea',
                'slug'          => 'lychee-tea',
                'description'   => 'Teh hitam premium dengan infus buah lychee segar, segar dan manis, cocok untuk bersantai.',
                'price'         => 20000,
                'is_available'  => true,
                'is_featured'   => true,
                'is_best_seller'=> false,
                'is_sample'     => false,
                'sort_order'    => 1,
            ],
            [
                'category_id'   => $nonKopi?->id,
                'name'          => 'Matcha',
                'slug'          => 'matcha',
                'description'   => 'Matcha premium grade ceremonial dengan susu lembut, rasa earthy yang khas dan menyegarkan.',
                'price'         => 25000,
                'is_available'  => true,
                'is_featured'   => true,
                'is_best_seller'=> false,
                'is_sample'     => false,
                'sort_order'    => 2,
            ],
            // DATA CONTOH non-kopi tambahan
            [
                'category_id'   => $nonKopi?->id,
                'name'          => 'Chocolate Milk',
                'slug'          => 'chocolate-milk',
                'description'   => 'Susu segar dengan cokelat premium belgi, creamy dan kaya rasa untuk semua usia.',
                'price'         => 22000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 3,
            ],
            [
                'category_id'   => $nonKopi?->id,
                'name'          => 'Strawberry Smoothie',
                'slug'          => 'strawberry-smoothie',
                'description'   => 'Smoothie buah stroberi segar yang diblender dengan yogurt, menyegarkan dan kaya vitamin.',
                'price'         => 24000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 4,
            ],
            [
                'category_id'   => $nonKopi?->id,
                'name'          => 'Taro Milk',
                'slug'          => 'taro-milk',
                'description'   => 'Minuman berbahan talas ungu dengan susu lembut, warna cantik dan rasa yang unik.',
                'price'         => 23000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 5,
            ],
            [
                'category_id'   => $nonKopi?->id,
                'name'          => 'Brown Sugar Milk',
                'slug'          => 'brown-sugar-milk',
                'description'   => 'Susu segar dengan gula aren asli yang memberikan rasa karamel alami yang khas.',
                'price'         => 22000,
                'is_available'  => true,
                'is_featured'   => false,
                'is_best_seller'=> false,
                'is_sample'     => true,
                'sort_order'    => 6,
            ],
        ];

        foreach ($menus as $menu) {
            Menu::updateOrCreate(
                ['slug' => $menu['slug']],
                $menu
            );
        }
    }
}
